# This is a Dockerfile

FROM alpine:latest

RUN apk update && apk --no-cache add g++ 

# Copy source code to the app directory
COPY test-client.cpp FileHandeling.h FileHandeling.cpp /app/
COPY received_file.txt /

# Set the working directory
WORKDIR /app

# Running all compilations needed 
RUN \
# Compile the FileHandeling lib
g++ -c FileHandeling.cpp -o FileHandeling.o && ar rcs libFileHandeling.a FileHandeling.o && \
# Compile the main app (Used just for running the server now)
g++ test-client.cpp -o test-client -L/app/ -lFileHandeling  

# Expose the port
EXPOSE 8080

# Command to run the server
CMD ["./test-client"]